export default [
  { code: 8, label: 'backspace' },
  { code: 9, label: 'tab' },

  { code: 13, label: 'enter' },

  { code: 16, label: 'shift' },
  { code: 17, label: 'ctrl' },
  { code: 18, label: 'alt' },

  { code: 20, label: 'caps' },

  { code: 27, label: 'escape' },

  { code: 32, label: 'space' },
  { code: 33, label: 'pageUp' },
  { code: 34, label: 'pageDown' },
  { code: 35, label: 'end' },
  { code: 36, label: 'home' },
  { code: 37, label: 'left' },
  { code: 38, label: 'up' },
  { code: 39, label: 'right' },
  { code: 40, label: 'down' },

  { code: 45, label: 'insert' },
  { code: 46, label: 'delete' },

  { code: 48, label: 'zero' },
  { code: 49, label: 'one' },
  { code: 50, label: 'two' },
  { code: 51, label: 'three' },
  { code: 52, label: 'four' },
  { code: 53, label: 'five' },
  { code: 54, label: 'six' },
  { code: 55, label: 'seven' },
  { code: 56, label: 'eight' },
  { code: 57, label: 'nine' },

  { code: 65, label: 'A' },
  { code: 66, label: 'B' },
  { code: 67, label: 'C' },
  { code: 68, label: 'D' },
  { code: 69, label: 'E' },
  { code: 70, label: 'F' },
  { code: 71, label: 'G' },
  { code: 72, label: 'H' },
  { code: 73, label: 'I' },
  { code: 74, label: 'J' },
  { code: 75, label: 'K' },
  { code: 76, label: 'L' },
  { code: 77, label: 'M' },
  { code: 78, label: 'N' },
  { code: 79, label: 'O' },
  { code: 80, label: 'P' },
  { code: 81, label: 'Q' },
  { code: 82, label: 'R' },
  { code: 83, label: 'S' },
  { code: 84, label: 'T' },
  { code: 85, label: 'U' },
  { code: 86, label: 'V' },
  { code: 87, label: 'W' },
  { code: 88, label: 'X' },
  { code: 89, label: 'Y' },
  { code: 90, label: 'Z' },

  { code: 91, label: 'superLeft' },
  { code: 92, label: 'superRight' },
  { code: 93, label: 'select' },

  { code: 96, label: 'num0' },
  { code: 97, label: 'num1' },
  { code: 98, label: 'num2' },
  { code: 99, label: 'num3' },
  { code: 100, label: 'num4' },
  { code: 101, label: 'num5' },
  { code: 102, label: 'num6' },
  { code: 103, label: 'num7' },
  { code: 104, label: 'num8' },
  { code: 105, label: 'num9' },
  { code: 106, label: 'multiply' },
  { code: 107, label: 'add' },

  { code: 109, label: 'subtract' },
  { code: 110, label: 'point' },
  { code: 111, label: 'divide' },
  { code: 112, label: 'F1' },
  { code: 113, label: 'F2' },
  { code: 114, label: 'F3' },
  { code: 115, label: 'F4' },
  { code: 116, label: 'F5' },
  { code: 117, label: 'F6' },
  { code: 118, label: 'F7' },
  { code: 119, label: 'F8' },
  { code: 120, label: 'F9' },
  { code: 121, label: 'F10' },
  { code: 122, label: 'F11' },
  { code: 123, label: 'F12' },

  { code: 144, label: 'numLock' },
  { code: 145, label: 'scrollLock' },

  { code: 186, label: 'semiColon' },
  { code: 187, label: 'equals' },
  { code: 188, label: 'comma' },
  { code: 189, label: 'dash' },
  { code: 190, label: 'dot' },
  { code: 191, label: 'forewardSlash' },
  { code: 192, label: 'graveAccent' },

  { code: 219, label: 'openBracket' },
  { code: 220, label: 'backSlash' },
  { code: 221, label: 'closeBracket' },
  { code: 222, label: 'singleQuote' }
]
